Introduce MongoDB.Extensions.Migration
SwissLife-OSS/mongo-extensions pull request #62
Opened 2022-07-08 14:18 UTC by TimHolzherr

MongoDB.Extensions.Migration allows to write migrations for MongoDB. 
Migrations are executed per document on read.
This allows for multi instance scenarios where different version of the application access the same database.

See [readme](https://github.com/SwissLife-OSS/mongo-extensions/blob/introduceMigration/src/Migration/Readme.md)

2022-07-19 16:07 UTC, nscheibe requested changes
Very well written. I just have some little questions or proposals which we maybe can shortly discuss. :)

2022-07-19 16:07 UTC, nscheibe commented on src/Migration/MigrationRunner.cs
> +        return _migrationRegistry.Keys.First() - 1;
Okay, I admit, if there is only one, two, three keys, then it does not count :)

2022-07-20 09:39 UTC, TimHolzherr commented on src/Migration/Readme.md
> +
Extended the example to have a valid Customer object

2022-07-20 11:28 UTC, nscheibe commented on src/Migration/Contracts/IMigration.cs
> +    public void Up(BsonDocument document);
I really had no clue about this, very interesting

2022-07-20 12:04 UTC, nscheibe approved these changes

2022-07-20 12:47 UTC, merged